Подключение сторонней библиотеки для написания слайдера
htmlacademy-javascript/1872127-kekstagram-25 pull request #11
Opened 2022-03-30 19:31 UTC by catch-a-chalk

+ Подключена библиотека noUiSlider в index.html
+ Создан модуль для слайдера
? Для его подключения инициализируем функцию, но что в ней написать?

- Не создан модуль для масштабирования изображения

2022-03-31 19:47 UTC, o-bender requested changes
забыл импортировать модуль в main.js
import './slider.js';

2022-03-31 19:47 UTC, o-bender commented on index.html
> +  <script src ="nouislider/nouislider.js"></script>
ещё у него css есть. проверь что бы тоже был подключен

2022-03-31 19:47 UTC, o-bender commented on js/slider.js
> +  } else {
в секция else никогда не сработает. так уж работают события в js

2022-03-31 19:47 UTC, o-bender commented on js/slider.js
> +      effectNames['none'].options
название эффекта бери из evt.target.value

2022-03-31 19:47 UTC, o-bender commented on js/slider.js
> +    imgUpload.input.classList.add('');
1. input-а тут нет
2. лучше делай так:
```
imgUpload.classList = `img-upload__preview effects__preview--${effectName}`
```

2022-03-31 19:47 UTC, o-bender commented on js/slider.js
> +const effectNone = document.querySelector('#effect-none');
сделай лучше так:
```
const effectControls = document.querySelectorAll('.effects__radio');
effectControls.forEach((effectControl) => effectControl.addEventListener('change', changeEffectHandler))
```

changeEffectHandler это обработчик вроде этого:
```
ffectNone.addEventListener('change', (evt) => {
  if (evt.target.checked) {
    imgUpload.input.classList.add('');
```

2022-04-01 10:01 UTC, catch-a-chalk commented on index.html
> +  <script src ="nouislider/nouislider.js"></script>
Проверил. Стили подключены в самом верху

2022-04-01 11:41 UTC, catch-a-chalk commented
Итак, вопросы:
- imgUpload.classList = `img-upload__preview effects__preview--${effectName}`. Я понимаю, что должен вставить буквально в фигурные скобки effectName, который будет вставлять соответствующее название из effectNames (none, chrome и прочее, но не понимаю, как это реализовать)
- changeEffectHandler - undefined, в качестве аргумента он уже был задан для effectControl, которые мы перебирали, но что записать внутрь него самого, если он - сам по себе обработчик? Тоже не въезжаю

2022-04-03 09:45 UTC, o-bender requested changes

2022-04-03 09:45 UTC, o-bender commented on js/scale-photo.js
> +controlValue.onchange = () => {
этот обработчик не нужен

2022-04-03 09:45 UTC, o-bender commented on js/scale-photo.js
> +    const amount = controlValue.value - SCALE_STEP;
а теперь давай по шагам посмотрим, что ты делаешь и что надо сделать:
1. сontrolValue.value - в самом начале там хранится строка '50%'
2. '50%' - 25 - результатом такого действия будет NaN. Намекает, что так не получится.

что надо сделать
1. сontrolValue.value - т.к. самом начале там хранится строка '50%' и в будущем так же будет храниться строка с цифрой и знаком %. то самое простое, что можно сделать отрезать знак %. сontrolValue.value.replace('%', '')
2. Теперь имя строку только с цифрами, её необходимо преобразовать к цифровому виду. Number
3. И вот теперь имея цифру мы можем из неё вычесть или прибавить SCALE_STEP

2022-04-03 09:45 UTC, o-bender commented on js/scale-photo.js
> +const onButton = () => {
убери пока что эту обёртку в виде функции

2022-04-03 09:45 UTC, o-bender commented on js/scale-photo.js
> +    imgUploadPreview.style.cssText = `transform: scale(0.'${amount}')`;
1. не стоит использовать cssText. он перезапишет весь css для элемента.
2. надо использовать style.transform
3. кавычки вокруг ${amount} лишние

2022-04-03 09:45 UTC, o-bender commented on js/scale-photo.js
> +const runDefaultScale = () => {
вот эту функцию стоит вызывать при открытии модального окна

2022-04-03 17:36 UTC, merged