Первая выгрузка задания 11.13 Надо подкачаться
htmlacademy-javascript/1872127-kekstagram-25 pull request #12
Opened 2022-04-06 20:03 UTC by catch-a-chalk

Сделано: 
+ добавлен модуль api.js
+ настроена загрузка данных с сервера, можно удалять data.js
+ почти настроена отправка формы: до середины лайва можно было наблюдать успешную отправку через вкладку Network, но при дальнейшей работе что-то пошло не так

Вопросы:
- не закрывается окно при отправке, нужно ли писать функцию closePhotoModal() внутрь initUploadWindow при успешной отправке?
- Дизайн блока ошибки нужно написать стилями?
-

2022-04-07 10:21 UTC, o-bender requested changes

2022-04-07 10:21 UTC, o-bender commented on js/api.js
> +const getData = (onSuccess) => {
Я бы, добавил ещё обработчик onFail. На случай если инет упал или сервер вернул ошибку.

2022-04-07 10:21 UTC, o-bender commented on js/api.js
> +    'https://25.javascript.pages.academy/404',
Ссылка неправильная, посмотри в задании там точно другая

2022-04-07 10:21 UTC, o-bender commented on js/api.js
> +      body: formData,
Линтер намекает, что formData тут нет. Зато есть body.

2022-04-07 10:21 UTC, o-bender commented on js/api.js
> +        showAlert('Не удалось отправить форму. Попробуйте еще раз');
Не надо тащить сюда showAlert. Модуль загрузки данных вообще не должен знать, ни о каких окошках и т.п. Он загружает данные и всё. Загрузил без ошибок вызвал onSuccess, случилась ошибка вызвал onFail. Что в onSuccess и onFail, как они реализованы его вообще не волнует.

2022-04-07 10:21 UTC, o-bender commented on js/api.js
> +    .catch((err) => {
Удали err. Ты его не используешь, а линтер нервничает.

2022-04-07 10:21 UTC, o-bender commented on js/main.js
> +  renderPhotos(photos.slice(0, PHOTOS_COUNT));
Можно просто `photos.slice(PHOTOS_COUNT)` так он просто первые 25 возьмёт

2022-04-07 10:21 UTC, o-bender commented on js/main.js
> +initUploadWindow(closePhotoModal());
1. Вот так `initUploadWindow(closePhotoModal);`, а то получается ты closePhotoModal сразу в main.js при открытии станички вызываешь.
2. Давай лучше оставим как было `initUploadWindow();`. Не будем пока усложнять.

2022-04-07 10:21 UTC, o-bender commented on js/validator.js
> +          onSuccess();
Вот тут надо бы вызвать функцию и показывать окошко подтверждающее успешность отправки. В разметке есть такой шаблон:
```
  <!-- Сообщение об успешной загрузке изображения -->
  <template id="success">
    <section class="success">
      <div class="success__inner">
        <h2 class="success__title">Изображение успешно загружено</h2>
        <button type="button" class="success__button">Круто!</button>
      </div>
    </section>
  </template>
```

2022-04-07 10:22 UTC, o-bender commented
По поводу дизайна блока ошибки есть уже шаблон для неё:
```
  <!-- Сообщение с ошибкой загрузки изображения -->
  <template id="error">
    <section class="error">
      <div class="error__inner">
        <h2 class="error__title">Ошибка загрузки файла</h2>
        <button type="button" class="error__button">Загрузить другой файл</button>
      </div>
    </section>
  </template>
```

2022-04-07 10:23 UTC, o-bender commented on js/validator.js
> +          onSuccess();
Тут ещё надо вызвать closePhotoModal().

2022-04-07 18:09 UTC, catch-a-chalk commented on js/api.js
> +    'https://25.javascript.pages.academy/404',
Я все понял. Изначально она была правильная, потом на лайве Игорь вручную поменял, и я по-глупости повторил

2022-04-08 17:02 UTC, o-bender requested changes

2022-04-08 17:02 UTC, o-bender commented on js/main.js
> +  renderPhotos(photos.slice(PHOTOS_COUNT));
Сорян, тут я был не прав) Нолик всё же нужен.

2022-04-08 17:02 UTC, o-bender commented on js/main.js
> +});
Обрабочик onFail не передал

2022-04-08 17:02 UTC, o-bender commented on js/validator.js
> +const initUploadWindow = (onSuccess, onFail) => {
вот ты объявил функцию
const initUploadWindow = (onSuccess, onFail) => {
тут ты предполагаешь, что должны придти два параметра onSuccess и onFail. Так же они предположительно будут функциями.

1. Но в прошлом пуше я предложил их убрать) т.к. слишком они всё усложняют.
2. Теперь когда ты их не передаёшь, а в main.js вот такая строка: initUploadWindow(); То их значения становятся undefined.
3. Но даже если бы они были функциями, то вот так на js делать всё равно не стоит.
```
 sendData(
        () => {
          onSuccess(() => { 
            successTemplate.cloneNode(true);
            closePhotoModal();
          });
          unblockSubmitButton();
        },
```

```
         // вот тут, ты подразумеваешь что onSuccess 100% передаётся в initUploadWindow. 
         // И что onSuccess принимает входным аргументом другую функцию.
         // На js я бы так делать не стал. 
         // Слишком много предположений и мест где это всё молча сломается.
          onSuccess(() => { 
            successTemplate.cloneNode(true);
            closePhotoModal();
          });
```

2022-04-08 17:02 UTC, o-bender commented on js/validator.js
> +const initUploadWindow = (onSuccess, onFail) => {
```
sendData(
        () => {
          closePhotoModal();
          unblockSubmitButton();
          const message = successTemplate.cloneNode(true)
          document.body.appendChild(message);
        },
        () => {
          closePhotoModal();
          unblockSubmitButton();
          const message = errorTemplate.cloneNode(true)
          document.body.appendChild(message);
        },
        new FormData(evt.target),
      );
```

2022-04-08 17:02 UTC, o-bender commented on js/api.js
> +          errorTemplate.cloneNode(true);
это дело тут точно не нужно. просто onFail

2022-04-10 11:43 UTC, catch-a-chalk commented
Исправлено:
- при открытии страницы автоматическая попытка отправки еще не заполненных данных: как следствие окно ошибки всплывало сразу.
- не работал обработчик закрытия окна при успешной отправке, хотя работал в случае ошибки
- изменено содержимое sendData в validator.js, значительная часть кода перенесена из main.js в валидатор для большей практичности и удобства

2022-04-10 12:53 UTC, merged