Первая проверка по домашнему заданию раздела 7
htmlacademy-javascript/1872127-kekstagram-25 pull request #6
Opened 2022-03-11 20:17 UTC by catch-a-chalk

2022-03-11 20:59 UTC, o-bender requested changes
запускай это дело в браузере. и прям по-строчно смотри, что происходит в коде. либо используй console.log, либо отладчик. про что за зверь такой отладчик по верхам объясняю тут [про отладчик](https://drive.google.com/file/d/1KkcGTM6Y0KiPF2PVyb2OpH1bTV97Urcm/view?usp=sharing)

2022-03-11 20:59 UTC, o-bender commented on js/main.js
> +renderPhotos(photos);
нет импорта

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +  photoBox.appendChild(photoElement);
photoElement в этой функции не существует

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +  photoBox.append(photos.map(renderPhoto));
в моём решении было кое что ещё

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +const similarPhotoFragment = document.createDocumentFragment(); // создаем узел
а зачем он? вроде бы ни где не используется

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +  photoElement.querySelector('.picture__comments').textContent = photoElement.comments; // то же
тут должно отображаться кол-во комментариев

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +  photoBox.appendChild(photoElement); // отрисуем шаблон в контейнере для фотографий пользователей
по идее это должно быть (и уже есть даже в двух вариантах) в renderPhotos.

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +}
а тут, в моём варианте есть return

2022-03-11 20:59 UTC, o-bender commented on js/render.js
> +photoBox.appendChild(similarPhotoFragment);
а зачем? создали пустой фрагмент и добавили его содержимое (т.е. ничего) в photoBox.

2022-03-12 18:23 UTC, catch-a-chalk commented on js/main.js
> +renderPhotos(photos);
> нет импорта

Исправлено

2022-03-12 18:25 UTC, catch-a-chalk commented on js/render.js
> +const similarPhotoFragment = document.createDocumentFragment(); // создаем узел
В задании было написано, что он нужен для вставки элементов, поэтому сделал, чтобы впоследствии разобраться, как использовать. Удаляю

2022-03-12 19:23 UTC, catch-a-chalk commented on js/render.js
> +  photoBox.appendChild(photoElement);
Строка удалена

2022-03-12 19:26 UTC, catch-a-chalk commented on js/render.js
> +  photoElement.querySelector('.picture__comments').textContent = photoElement.comments; // то же
Следовательно, меняю .textContent на .length?

2022-03-12 19:28 UTC, catch-a-chalk commented on js/render.js
> +}
Исправил

2022-03-12 19:29 UTC, catch-a-chalk commented on js/render.js
> +photoBox.appendChild(similarPhotoFragment);
переменная similarPhotoFragment удалена

2022-03-12 19:41 UTC, catch-a-chalk commented on js/render.js
> +  photoBox.appendChild(photoElement); // отрисуем шаблон в контейнере для фотографий пользователей
Не понимаю, что именно. Отрисовка шаблона?

2022-03-13 18:47 UTC, o-bender requested changes

2022-03-13 18:47 UTC, o-bender commented on js/render.js
> +  photoBox.appendChild(photoElement); // отрисуем шаблон в контейнере для фотографий пользователей
Вот тут
```
const renderPhoto = (photoElement) => {
  photoElement = photoTemplate.cloneNode(true); // копируем шаблон и отрисовываем его в контейнере
  photoBox.appendChild(photoElement)
```

конкретно эта строка: ` photoBox.appendChild(photoElement)`. Добавляет элемент photoElement в photoBox. Т.е. рисует элемент фотографии на экране.


```
const renderPhotos = (photos) => {
  photoBox.querySelectorAll('.picture').forEach((element) => element.remove());
  photoBox.append(photos.map(renderPhoto));
```
и вот эта строка: `photoBox.append(photos.map(renderPhoto));` добавляет все созданные элементы в photoBox. Рисует все созданные элементы фотографий на экране. Т.е. зачем-то опять их рисует. Хотя они уже нарисованы.
0. надо оставить, что-то одно.
1. если используешь append, то должно быть так `photoBox.append(...photos.map(renderPhoto));` 
2. если используешь `photoBox.appendChild(photoElement)`, то его надо как раз добавлять в DocumentFragmet, который был создан, но не использовался. А затем DocumentFragment добавлять в photoBox.
3. Проверить, что всё это дело работает :)

2022-03-13 18:55 UTC, o-bender commented on js/render.js
> +  photoElement.querySelector('.picture__comments').textContent = photoElement.comments; // то же
Внимательно прочти и разберись в каждой строчке.
```
const renderPhoto = (photoElement) => {  // приходят данные
  const photoElement = photoTemplate.cloneNode(true);  // оп и в туже самую переменную кладём DOM элемент
  // а дальше photoElement слева это DOM элемент, а справа это уже объект? К сожалению так не получится
  photoElement.querySelector('.picture__img').src = photoElement.url; 
  photoElement.querySelector('.picture__likes').textContent = photoElement.likes;
  photoElement.querySelector('.picture__comments').textContent = photoElement.comments; 
```

```
const renderPhoto = (photo) => {
  const photoElement = photoTemplate.cloneNode(true);\
  photoElement.querySelector('.picture__img').src = photo.url;
  photoElement.querySelector('.picture__likes').textContent = photo.likes;
  photoElement.querySelector('.picture__comments').textContent = photo.comments.length;
  return photoElement;
```

Крайне важно понимать каждый символ в своём коде. Для начала своём :) Если какой-то не понятен, значит надо выписать пример непонятки, понять, что конкретно не понятно и загуглить или задать вопрос мне.

2022-03-15 15:43 UTC, o-bender requested changes

2022-03-15 15:43 UTC, o-bender commented on js/render.js
> +    photoBox.append(photoFragment);
эту строчку надо вынести из цикла. исправь и объясни мне в чате почему это должно быть так:)
```
const renderPhotos = (photos) => {
  photos.forEach((item) => {
    photoFragment.appendChild(renderPhoto(item));
  });
  photoBox.appendChild(photoFragment);
}
```

2022-03-15 15:43 UTC, o-bender commented on js/render.js
> +// const photoTemplate = document.body.querySelector('#picture').content;
не используемый код в комментах удали, это расценивается как нарушение критерия на финальной проверке

2022-03-15 21:04 UTC, merged