Добавление обработчиков открытия и закрытия модального окна (Работа с событиями)
htmlacademy-javascript/1872127-kekstagram-25 pull request #7
Opened 2022-03-18 14:31 UTC by catch-a-chalk

Добавлено:
+ модуль processing-modal.js
+ атрибуты к тегам form (адрес отправки и метод) и input (maxlength и tabindex)
+ получены файлы (валидатор pristine)

Вопрос:
- не добавлял required, так как в разметке они уже есть на том же выборе фотографии, а к фильтрам ставить не вижу смысла, может, что упустил?
- по ТЗ мы открываем окна при изменении значения в #upload-file, но в ДЗ обращаемся к событию onclick, это правильно?

2022-03-18 15:15 UTC, o-bender requested changes

2022-03-18 15:15 UTC, o-bender commented on index.html
> +                  <input class="text__hashtags" name="hashtags" placeholder="#ХэшТег" minlength="2" maxlength="20">
> максимальная длина **одного** хэш-тега 20 символов, включая решётку;
а это поле для ввода нескольких тегов.

2022-03-18 15:15 UTC, o-bender commented on js/processing-modal.js
> +photoProcessingClose.addEventListener('keydown', function (evt) {
замени на стрелочную функцию

2022-03-18 15:15 UTC, o-bender commented on js/processing-modal.js
> +photoProcessingOpen.addEventListener('click', () => {
код отсюда и до конца файла помести в функцию и вызывай её в main.js.

2022-03-20 14:28 UTC, catch-a-chalk commented
Впал в ступор:
- Мы должны выполнить все требования по загрузке изображения или просто понять, как это работает https://up.htmlacademy.ru/profession/frontender/12/javascript/25/project/kekstagram#kekstagram-1-1
- Редактирование изображения, пункт 2.2 https://up.htmlacademy.ru/profession/frontender/12/javascript/25/project/kekstagram#kekstagram-2-2
Имеет смысл ставить в разметке атрибут step напротив соответствующих импутов эффектов или на это тоже напишем код?
- Не понимаю, как структурировать написание требования для валидации хэш-тегов: в демонстрации несколько импутов, в нашем случае два: импут тега и textarea комментария, каждый раз обращаться к нему по-новому или все требования можно как-то разместить в одном обращении?

2022-03-22 08:02 UTC, o-bender requested changes

2022-03-22 08:02 UTC, o-bender commented on js/processing-modal.js
> +  photoProcessingOpen.addEventListener('click', () => {
тут надо использовать событие change

2022-03-22 08:02 UTC, o-bender commented on js/processing-modal.js
> +import {isEscapeKey, isEnterKey} from './util';
пропущено .js

2022-03-22 08:02 UTC, o-bender commented on js/validator.js
> +  errorTextTag: 'span',
используй лучше div или p. а то span наверняка будет плохо выглядеть

2022-03-22 08:02 UTC, o-bender commented on js/validator.js
> +function validateHashtag (value) {
замени на стрелочную функцию

2022-03-22 08:02 UTC, o-bender commented on js/validator.js
> +pristine.addValidator(
отсюда и до конца надо переместить в функцию что-нибудь вроде initUploadWindow. и вызывать её в main.js. сейчас этот файл ни где не импортируется и браузер о нём не знает, по этому ничего не работает.

2022-03-22 08:02 UTC, o-bender commented on js/validator.js
> +  ruleHashtag,
так это работать не будет.но будет так:
```
pristine.addValidator(
  form.querySelector('.text__hashtags'),
  (value) => ruleHashtag.test(value),
  'Хэш-тег должен состоять только из букв и чисел'
)
```
но и это ещё не всё. регулярка работает с одним тегом. а в строке тегов может быть несколько. т.е. тут надо разбить строку по пробелам методом split(/\s+/). ещё стоит использовать trim().toLowerCase(). теги обычно регистро-независимы и ведущие и замыкающие пробелы нам тоже не нужны.
получится так value = value.tirim().toLowerCase().split(/\s+/)

2022-03-22 08:02 UTC, o-bender commented on js/validator.js
> +  'От 2 до 20 символов, включая #'
а разве так? мне казалось что теги не обязательны. т.е. что фотку можно загрузить без тега

2022-03-23 14:21 UTC, o-bender requested changes

2022-03-23 14:21 UTC, o-bender commented on js/processing-modal.js
> +  renderPhotos();
зачем это тут?

2022-03-23 14:21 UTC, o-bender commented on js/validator.js
> +    validateHashtag(),
вызов тут не нужен

2022-03-23 14:21 UTC, o-bender commented on js/validator.js
> +      if (!ruleHashtag.test(tags)) {
тут нужен цикл

2022-03-23 14:21 UTC, o-bender commented on js/validator.js
> +    }
а где текст ошибки?)

2022-03-25 12:54 UTC, merged